### ISSUE TITLE
not working in some cases with a custom /etc/docker/daemon.json

### ISSUE THREAD

**Issue by naleiht** [geomapfish/getting_started#2]
### Current Behavior
Users cannot start the demo using `./install.sh` and installing everything locally (including database).

### Expected Behavior

App should start on port 8484 without errors. It should use the local database (i.e. docker container provided with install.sh script)

### Steps to Reproduce

1. Install a fresh Ubuntu flavor distribution (i.e. Pop!_OS 22.04 LTS x86_64 installation)
2. Install all prerequisites
3. By default, /etc/docker/daemon.json does not exist.
4. Add a basic /etc/docker/daemon.json (i.e. to override storage default config)
     ```
    {
        "data-root": "/storage/docker"
    }
    ```
5. Run `./install.sh` and kind of say yes to everything, also to install a local database.
6. Everything should be fine, but the app won't work correctly.
7. In docker logs file, you should see some connection error to `pg-gs.camptocamp.com`
    
### Additional Information

I do not override default network, however the presence of /etc/docker/daemon.json trigger the if case:
```
dbhost=172.17.0.1
# Check if the default network was overriden on this server
if [ -f /etc/docker/daemon.json ]
then
    dbhost=`sed -r 's/.*"bip" *\: *"([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+).*/\1/' /etc/docker/daemon.json`
fi
```
A simple fix could be an additional condition with a regex searching the presence of the string. What do you think ?

**Comment by remyguillaume** [comment]
Hi @naleiht 

Sorry for the late answer, I've just noticed your issue.
I'll try to test this during the next tags. Thanks for your patience.
