### ISSUE TITLE
Impossibilité de me reconnecter à mon application GeoMapFish. Que faire ? 

### ISSUE THREAD

**Issue by henriquerolao** [geomapfish/getting_started#5]
Quand je lance mon application et que j'applique mon login et mot de passe alors rien ne se passe. 

Sur Docker, je peux voir les lignes suivantes s'afficher dans le détail de la console : 
| 2023-02-15T16:12:17.060528010Z [2023-02-15 16:12:17 +0000] [52] [INFO ] Invalid referer for /login: 'https://desktop-plri307:8484/'
| [2023-02-15 16:12:17 +0000] [52] [INFO ] User 'admin' logged in.
| [2023-02-15 16:12:17 +0000] [52] [WARNI] CORS query not allowed for origin=https://desktop-plri307:8484, service=login

Que puis-je faire pour remédier à cela ?

**Comment by maltaesousa** [comment]
Problème réglé suite à une visioconférence
